[tool.poetry]
name = "build-github-readme"
version = "0.1.0"
description = "A tool to build my GitHub README file."
authors = ["Myles Braithwaite <me@mylesbraithwaite.com>"]
readme = "README.md"
packages = [{include = "build_readme"}]

[tool.poetry.dependencies]
python = "^3.9"
click = "^8.1.3"
feedparser = "^6.0.10"
pyquery = "^2.0.0"
pytz = "^2022.7.1"
requests = "^2.28.2"

[tool.poetry.group.dev.dependencies]
black = "^23.1.0"
isort = "^5.12.0"
pytest = "^7.2.2"
ruff = "^0.0.256"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
build-readme = 'build_readme.cli:cli'
